<?php

namespace Indago\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
	public function getMenu(){
		$em = $this->getEntityManager();
		$query = $em->createQuery(
				'SELECT menu
			    FROM IndagoGeneralBundle:Menu menu
				ORDER BY menu.menuId'
		);	
		$menus = $query->getResult();
		echo count($menus);die();
		return  $menus;
		
	}
	
	public function getMenuUser(){
		$em = $this->getEntityManager();
		$query = $em->createQuery(
				'SELECT menu
			    FROM IndagoGeneralBundle:Menu menu
				ORDER BY menu_id'
		);
		$menus = $query->getResult();
		return  $menus;
	}
}
